### ISSUE TITLE
git submodule update --init fails with Permission denied

### ISSUE THREAD

**Issue by rpm0372** [yoppeh/efi-clang#1]
trying 
$ git submodule update --init
right after I clone produces the following output:

Submodule 'efi' (git@github.com:yoppeh/efi.git) registered for path 'efi'
Cloning into 'E:/github/efi-clang/efi'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:yoppeh/efi.git' into submodule path 'E:/github/efi-clang/efi' failed
Failed to clone 'efi'. Retry scheduled
Cloning into 'E:/github/efi-clang/efi'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:yoppeh/efi.git' into submodule path 'E:/github/efi-clang/efi' failed
Failed to clone 'efi' a second time, aborting

**Comment by yoppeh** [comment]
I modified it to use https in the .gitmodules. See if that fixes it...

**Comment by rpm0372** [comment]
yep. ty
